### ISSUE TITLE
在 NPM 將 qieyun 標記為棄置

### ISSUE THREAD

**Issue by syimyuzya** [nk2028/tshet-uinh-js#45]
剛在 CI 上試了一下，不過沒有成功。

目前 qieyun 仍未標上 deprecated。

**Comment by ayaka14732** [comment]
在 npm 的網頁上改了，但是試圖使用命令定製 deprecated message 的時候失敗了

**Comment by syimyuzya** [comment]
> 在 npm 的網頁上改了，但是試圖使用命令定製 deprecated message 的時候失敗了

咦🤔奇妙

好在如果用戶願意上 NPM 或 Github 上查一下的話，還是能查得到新名字 tshet-uinh 的（NPM 可以用「qieyun」搜到，Github 用舊地址會自動重定向）。

所以暫且可以過陣子再看這個問題，如果還是不行的話，再想辦法。

**Comment by ayaka14732** [comment]
搞好了，之前是因為沒有在命令行執行 `npm login`
